[project]
name = "beian"
version = "0.1.0"
description = "Query ICP beian like whois"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ddddocr>=1.6.1",
    "playwright>=1.40",
    "requests>=2.31",
]

[project.scripts]
beian = "beian.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["beian"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
